class AppData {
  //HOSTELS

  static List<Map<String, dynamic>> hostels = [
    {
      "id": "h1",
      "name": "Green View Hostel",
      "location": "Zindabazar",
      "price": 3500,
      "rating": 4.5,
      "available": true,
      "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
      "roomType": "Shared Room",
      "capacity": "3 Students",
      "department": "CSE Students",
      "wifi": true,
      "meals": true,
      "security": true,
      "experience": "Peaceful environment and good food.",
    },
    {
      "id": "h2",
      "name": "Student Hub",
      "location": "Amberkhana",
      "price": 2500,
      "rating": 4.2,
      "available": true,
      "image": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
      "roomType": "Shared Room",
      "capacity": "2 Students",
      "department": "All Departments",
      "wifi": true,
      "meals": false,
      "security": true,
      "experience": "Affordable and friendly environment.",
    },
    {
      "id": "h3",
      "name": "City Nest",
      "location": "Shahi Eidgah",
      "price": 7000,
      "rating": 4.8,
      "available": false,
      "image": "https://images.unsplash.com/photo-1555854877-bab0e564b8d5",
      "roomType": "Single Room",
      "capacity": "1 Student",
      "department": "CSE Students",
      "wifi": false,
      "meals": true,
      "security": true,
      "experience": "Premium hostel with best facilities.",
    },
    {
      "id": "h4",
      "name": "Royal Stay Hostel",
      "location": "Mirabazar",
      "price": 4200,
      "rating": 4.3,
      "available": true,
      "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
      "roomType": "Shared Room",
      "capacity": "2–3 Students",
      "department": "English",
      "wifi": true,
      "meals": true,
      "security": false,
      "experience": "Comfortable stay with average security but good food.",
    },
    {
      "id": "h5",
      "name": "Dream Nest",
      "location": "Tilagor",
      "price": 3000,
      "rating": 4.1,
      "available": true,
      "image": "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6",
      "roomType": "Shared Room",
      "capacity": "2 Students",
      "department": "BBA",
      "wifi": true,
      "meals": false,
      "security": false,
      "experience": "Simple living with basic facilities.",
    },
    {
      "id": "h6",
      "name": "Comfort Home Hostel",
      "location": "Ambarkhana",
      "price": 2800,
      "rating": 4.0,
      "available": false,
      "image": "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
      "roomType": "Shared Room",
      "capacity": "3 Students",
      "department": "EEE",
      "wifi": false,
      "meals": true,
      "security": false,
      "experience": "Budget friendly but limited facilities.",
    },
    {
      "id": "h7",
      "name": "Elite Boys Hostel",
      "location": "Zindabazar",
      "price": 6000,
      "rating": 4.7,
      "available": true,
      "image": "https://images.unsplash.com/photo-1484154218962-a197022b5858",
      "roomType": "Single Room",
      "capacity": "1 Student",
      "department": "CSE Students",
      "wifi": true,
      "meals": true,
      "security": true,
      "experience": "Premium hostel with full facilities.",
    },
    {
      "id": "h8",
      "name": "Sylhet Ladies Hostel",
      "location": "Subidbazar",
      "price": 5000,
      "rating": 4.6,
      "available": true,
      "image": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
      "roomType": "Shared Room",
      "capacity": "2 Students",
      "department": "All Departments",
      "wifi": true,
      "meals": true,
      "security": true,
      "experience": "Safe and comfortable environment for girls.",
    },
  ];

  // SAVED HOSTELS
  static List<Map<String, dynamic>> savedHostels = [];

  //ROOMMATES

  static List<Map<String, dynamic>> roommates = [
    {
      "name": "Rahim Ahmed",
      "department": "CSE",
      "lifestyle": "Quiet, Study-focused",
      "bio": "Focuses on studies, prefers silent environment.",
      "year": "2nd Year",
    },
    {
      "name": "Sadia Islam",
      "department": "CSE",
      "lifestyle": "Study-focused",
      "bio": "Friendly and disciplined student.",
      "year": "1st Year",
    },
    {
      "name": "Tanvir Hasan",
      "department": "EEE",
      "lifestyle": "Social",
      "bio": "Likes group study and teamwork.",
      "year": "3rd Year",
    },
    {
      "name": "Nusrat Jahan",
      "department": "BBA",
      "lifestyle": "Quiet",
      "bio": "Prefers clean and peaceful environment.",
      "year": "2nd Year",
    },
    {
      "name": "Arif Hossain",
      "department": "English",
      "lifestyle": "Quiet, Study-focused",
    },
  ];
}
