// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAhsyo_XYmsUbWSWB8odI15cE5US_rSoY',
    appId: '1:395113593887:web:824f48285a9aa6b018292a',
    messagingSenderId: '395113593887',
    projectId: 'nan-nest-finder',
    authDomain: 'nan-nest-finder.firebaseapp.com',
    storageBucket: 'nan-nest-finder.firebasestorage.app',
    measurementId: 'G-GPB0SZ1RKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQr0gg86OIP8nopGps_Wghnt1ilmLev6k',
    appId: '1:395113593887:android:b69bf51ec2dcf3fc18292a',
    messagingSenderId: '395113593887',
    projectId: 'nan-nest-finder',
    storageBucket: 'nan-nest-finder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAn8smKsKQ7rItzK1-K5gdNl5Vo96uN7k',
    appId: '1:395113593887:ios:105090e07d73f32c18292a',
    messagingSenderId: '395113593887',
    projectId: 'nan-nest-finder',
    storageBucket: 'nan-nest-finder.firebasestorage.app',
    iosBundleId: 'com.example.nanNestfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAn8smKsKQ7rItzK1-K5gdNl5Vo96uN7k',
    appId: '1:395113593887:ios:105090e07d73f32c18292a',
    messagingSenderId: '395113593887',
    projectId: 'nan-nest-finder',
    storageBucket: 'nan-nest-finder.firebasestorage.app',
    iosBundleId: 'com.example.nanNestfinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAhsyo_XYmsUbWSWB8odI15cE5US_rSoY',
    appId: '1:395113593887:web:731a1c95b632170118292a',
    messagingSenderId: '395113593887',
    projectId: 'nan-nest-finder',
    authDomain: 'nan-nest-finder.firebaseapp.com',
    storageBucket: 'nan-nest-finder.firebasestorage.app',
    measurementId: 'G-39E9Q5Y43R',
  );
}
